// Author: Igor compiler
// Compiler version: igorc 2.1.1
// DO NOT EDIT THIS FILE - it is machine generated

import * as Igor from './igor';

export enum FileAttachmentOrderBy {
    Id = 1,
    FileSize = 2,
    OriginalFilename = 3,
    ContentType = 4,
    PersonnelId = 5,
    PersonnelName = 6,
    CreatedAt = 7,
}

export namespace FileAttachmentOrderBy {
    export function toJson(value: FileAttachmentOrderBy): Igor.Json.JsonValue {
        return toJsonKey(value);
    }

    export function fromJson(json: Igor.Json.JsonValue): FileAttachmentOrderBy {
        return fromJsonKey(json);
    }

    export function toJsonKey(value: FileAttachmentOrderBy): Igor.Json.JsonValue {
        switch (value) {
            case FileAttachmentOrderBy.Id: return 'id';
            case FileAttachmentOrderBy.FileSize: return 'file_size';
            case FileAttachmentOrderBy.OriginalFilename: return 'original_filename';
            case FileAttachmentOrderBy.ContentType: return 'content_type';
            case FileAttachmentOrderBy.PersonnelId: return 'personnel_id';
            case FileAttachmentOrderBy.PersonnelName: return 'personnel_name';
            case FileAttachmentOrderBy.CreatedAt: return 'created_at';
            default: throw new Error(`Invalid FileAttachmentOrderBy value: ${value}`);
        }
    }

    export function fromJsonKey(json: Igor.Json.JsonValue): FileAttachmentOrderBy {
        switch (json) {
            case 'id': return FileAttachmentOrderBy.Id;
            case 'file_size': return FileAttachmentOrderBy.FileSize;
            case 'original_filename': return FileAttachmentOrderBy.OriginalFilename;
            case 'content_type': return FileAttachmentOrderBy.ContentType;
            case 'personnel_id': return FileAttachmentOrderBy.PersonnelId;
            case 'personnel_name': return FileAttachmentOrderBy.PersonnelName;
            case 'created_at': return FileAttachmentOrderBy.CreatedAt;
            default: throw new Error(`Invalid FileAttachmentOrderBy value: ${json}`);
        }
    }
}
