// Author: Igor compiler
// Compiler version: igorc 2.1.1
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as AuthProtocol from './auth-protocol.data';
import * as CommonProtocol from './common-protocol.data';
import * as DataProtocol from './data-protocol.data';
import * as DbProtocol from './db-protocol.data';

@Injectable({
    providedIn: 'root',
})
export class HyperionAuthService {
    public baseUrl = '';

    constructor(private http: HttpClient) { }

    public getPersonnelStatus(): Observable<AuthProtocol.PersonnelStatusResponse> {
        return this.http
            .get(`${this.baseUrl}/api/auth/personnel/status`)
            .pipe(
                map(response => AuthProtocol.PersonnelStatusResponse.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public loginPersonnel(request: AuthProtocol.PersonnelLoginRequest): Observable<AuthProtocol.PersonnelLoginResponse> {
        const options = { headers: new HttpHeaders({'Content-Type': 'application/json' }) };

        return this.http
            .post(`${this.baseUrl}/api/auth/personnel/login`, request.toJson(), options)
            .pipe(
                map(response => AuthProtocol.PersonnelLoginResponse.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public logoutPersonnel(request: CommonProtocol.Empty): Observable<DataProtocol.GenericResponse> {
        const options = { headers: new HttpHeaders({'Content-Type': 'application/json' }) };

        return this.http
            .put(`${this.baseUrl}/api/auth/personnel/logout`, request.toJson(), options)
            .pipe(
                map(response => DataProtocol.GenericResponse.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public getMyPersonnelProfile(): Observable<DbProtocol.PersonnelAccountProfile> {
        return this.http
            .get(`${this.baseUrl}/api/auth/personnel/profile`)
            .pipe(
                map(response => DbProtocol.PersonnelAccountProfile.fromJson(response as Igor.Json.JsonValue))
            );
    }
}
