// Author: Igor compiler
// Compiler version: igorc 2.1.1
// DO NOT EDIT THIS FILE - it is machine generated

import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import * as Igor from './igor';
import * as DataProtocol from './data-protocol.data';
import * as DbProtocol from './db-protocol.data';
import * as ParameterProtocol from './parameter-protocol.data';

@Injectable({
    providedIn: 'root',
})
export class HyperionParameterService {
    public baseUrl = '';

    constructor(private http: HttpClient) { }

    public getParameters(projectId: number): Observable<DataProtocol.Collection<DataProtocol.TreeNode<DbProtocol.Parameter>>> {
        return this.http
            .get(`${this.baseUrl}/api/parameters/project/${projectId}`)
            .pipe(
                catchError(response => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403: return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                            case 500: return throwError(DataProtocol.InternalServerError.fromJson(response.error));
                        }
                    }
                    throwError(response);
                }),
                map(response => DataProtocol.Collection.instanceJsonSerializer<DataProtocol.TreeNode<DbProtocol.Parameter>>(DataProtocol.TreeNode.instanceJsonSerializer<DbProtocol.Parameter>(DbProtocol.Parameter)).fromJson(response as Igor.Json.JsonValue))
            );
    }

    public getParameter(id: number): Observable<DbProtocol.Parameter> {
        return this.http
            .get(`${this.baseUrl}/api/parameters/${id}`)
            .pipe(
                catchError(response => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 403: return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                            case 404: return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                            case 500: return throwError(DataProtocol.InternalServerError.fromJson(response.error));
                        }
                    }
                    throwError(response);
                }),
                map(response => DbProtocol.Parameter.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public createParameter(request: ParameterProtocol.CreateParameterRequest, projectId: number): Observable<DbProtocol.Parameter> {
        const options = { headers: new HttpHeaders({'Content-Type': 'application/json' }) };

        return this.http
            .post(`${this.baseUrl}/api/parameters/project/${projectId}`, request.toJson(), options)
            .pipe(
                catchError(response => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400: return throwError(DataProtocol.BadRequestError.instanceJsonSerializer<ParameterProtocol.ParameterCreateError>(ParameterProtocol.ParameterCreateError).fromJson(response.error));
                            case 403: return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                            case 500: return throwError(DataProtocol.InternalServerError.fromJson(response.error));
                        }
                    }
                    throwError(response);
                }),
                map(response => DbProtocol.Parameter.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public renameParameter(request: ParameterProtocol.RenameParameterRequest, id: number): Observable<DbProtocol.Parameter> {
        const options = { headers: new HttpHeaders({'Content-Type': 'application/json' }) };

        return this.http
            .put(`${this.baseUrl}/api/parameters/${id}`, request.toJson(), options)
            .pipe(
                catchError(response => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400: return throwError(DataProtocol.BadRequestError.instanceJsonSerializer<ParameterProtocol.ParameterRenameError>(ParameterProtocol.ParameterRenameError).fromJson(response.error));
                            case 403: return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                            case 404: return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                            case 500: return throwError(DataProtocol.InternalServerError.fromJson(response.error));
                        }
                    }
                    throwError(response);
                }),
                map(response => DbProtocol.Parameter.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public deleteParameter(id: number): Observable<DataProtocol.GenericResponse> {
        return this.http
            .delete(`${this.baseUrl}/api/parameters/${id}`)
            .pipe(
                catchError(response => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400: return throwError(DataProtocol.BadRequestError.instanceJsonSerializer<ParameterProtocol.ParameterDeleteError>(ParameterProtocol.ParameterDeleteError).fromJson(response.error));
                            case 403: return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                            case 404: return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                            case 500: return throwError(DataProtocol.InternalServerError.fromJson(response.error));
                        }
                    }
                    throwError(response);
                }),
                map(response => DataProtocol.GenericResponse.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public addParameterValue(request: ParameterProtocol.AddParameterValueRequest, id: number): Observable<DbProtocol.Parameter> {
        const options = { headers: new HttpHeaders({'Content-Type': 'application/json' }) };

        return this.http
            .post(`${this.baseUrl}/api/parameters/${id}/value/add`, request.toJson(), options)
            .pipe(
                catchError(response => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400: return throwError(DataProtocol.BadRequestError.instanceJsonSerializer<ParameterProtocol.ParameterValueAddError>(ParameterProtocol.ParameterValueAddError).fromJson(response.error));
                            case 403: return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                            case 404: return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                            case 500: return throwError(DataProtocol.InternalServerError.fromJson(response.error));
                        }
                    }
                    throwError(response);
                }),
                map(response => DbProtocol.Parameter.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public renameParameterValue(request: ParameterProtocol.RenameParameterValueRequest, id: number): Observable<DbProtocol.Parameter> {
        const options = { headers: new HttpHeaders({'Content-Type': 'application/json' }) };

        return this.http
            .put(`${this.baseUrl}/api/parameters/${id}/value/rename`, request.toJson(), options)
            .pipe(
                catchError(response => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400: return throwError(DataProtocol.BadRequestError.instanceJsonSerializer<ParameterProtocol.ParameterValueRenameError>(ParameterProtocol.ParameterValueRenameError).fromJson(response.error));
                            case 403: return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                            case 404: return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                            case 500: return throwError(DataProtocol.InternalServerError.fromJson(response.error));
                        }
                    }
                    throwError(response);
                }),
                map(response => DbProtocol.Parameter.fromJson(response as Igor.Json.JsonValue))
            );
    }

    public removeParameterValue(request: ParameterProtocol.RemoveParameterValueRequest, id: number): Observable<DbProtocol.Parameter> {
        const options = { headers: new HttpHeaders({'Content-Type': 'application/json' }) };

        return this.http
            .put(`${this.baseUrl}/api/parameters/${id}/value/remove`, request.toJson(), options)
            .pipe(
                catchError(response => {
                    if (response instanceof HttpErrorResponse) {
                        switch (response.status) {
                            case 400: return throwError(DataProtocol.BadRequestError.instanceJsonSerializer<ParameterProtocol.ParameterValueRemoveError>(ParameterProtocol.ParameterValueRemoveError).fromJson(response.error));
                            case 403: return throwError(DataProtocol.ForbiddenError.fromJson(response.error));
                            case 404: return throwError(DataProtocol.NotFoundError.fromJson(response.error));
                            case 500: return throwError(DataProtocol.InternalServerError.fromJson(response.error));
                        }
                    }
                    throwError(response);
                }),
                map(response => DbProtocol.Parameter.fromJson(response as Igor.Json.JsonValue))
            );
    }
}
