%% @author Igor compiler
%% @doc Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-module(protocol_settings).

-include_lib("stdlib/include/assert.hrl").
-include("protocol_settings.hrl").

-export([
    settings_to_json/1,
    settings_from_json/1,
    settings_update_request_to_json/1,
    settings_update_request_from_json/1
]).

-export_type([
    settings/0,
    settings_update_request/0
]).

-type settings() :: #settings{}.
-type settings_update_request() :: #settings_update_request{}.

-spec settings_to_json(settings()) -> igor_json:json_object().

settings_to_json(Record) ->
    #settings{personnel_session_duration = PersonnelSessionDuration} = Record,
    ?assert(PersonnelSessionDuration =/= undefined),
    #{
        <<"personnel_session_duration">> => igor_json:pack(PersonnelSessionDuration, int)
    }.

-spec settings_from_json(igor_json:json_object()) -> settings().

settings_from_json(Json) ->
    PersonnelSessionDuration = igor_json:parse(Json, <<"personnel_session_duration">>, int),
    #settings{personnel_session_duration = PersonnelSessionDuration}.

-spec settings_update_request_to_json(settings_update_request()) -> igor_json:json_object().

settings_update_request_to_json(Record) ->
    #settings_update_request{personnel_session_duration = PersonnelSessionDuration} = Record,
    #{
        <<"personnel_session_duration">> => igor_json:pack(PersonnelSessionDuration, int)
    }.

-spec settings_update_request_from_json(igor_json:json_object()) -> settings_update_request().

settings_update_request_from_json(Json) ->
    PersonnelSessionDuration = igor_json:parse(Json, <<"personnel_session_duration">>, int, undefined),
    #settings_update_request{personnel_session_duration = PersonnelSessionDuration}.

