%% @author Igor compiler
%% @doc Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-module(protocol_parameter).

-include_lib("stdlib/include/assert.hrl").
-include("protocol_parameter.hrl").

-export([
    parameter_create_error_to_string/1,
    parameter_create_error_from_string/1,
    parameter_create_error_to_json/1,
    parameter_create_error_from_json/1,
    parameter_rename_error_to_string/1,
    parameter_rename_error_from_string/1,
    parameter_rename_error_to_json/1,
    parameter_rename_error_from_json/1,
    parameter_delete_error_to_string/1,
    parameter_delete_error_from_string/1,
    parameter_delete_error_to_json/1,
    parameter_delete_error_from_json/1,
    parameter_value_add_error_to_string/1,
    parameter_value_add_error_from_string/1,
    parameter_value_add_error_to_json/1,
    parameter_value_add_error_from_json/1,
    parameter_value_rename_error_to_string/1,
    parameter_value_rename_error_from_string/1,
    parameter_value_rename_error_to_json/1,
    parameter_value_rename_error_from_json/1,
    parameter_value_remove_error_to_string/1,
    parameter_value_remove_error_from_string/1,
    parameter_value_remove_error_to_json/1,
    parameter_value_remove_error_from_json/1,
    create_parameter_request_to_json/1,
    create_parameter_request_from_json/1,
    rename_parameter_request_to_json/1,
    rename_parameter_request_from_json/1,
    add_parameter_value_request_to_json/1,
    add_parameter_value_request_from_json/1,
    rename_parameter_value_request_to_json/1,
    rename_parameter_value_request_from_json/1,
    remove_parameter_value_request_to_json/1,
    remove_parameter_value_request_from_json/1
]).

-export_type([
    create_parameter_request/0,
    parameter_create_error/0,
    rename_parameter_request/0,
    parameter_rename_error/0,
    parameter_delete_error/0,
    add_parameter_value_request/0,
    parameter_value_add_error/0,
    rename_parameter_value_request/0,
    parameter_value_rename_error/0,
    remove_parameter_value_request/0,
    parameter_value_remove_error/0
]).

-type create_parameter_request() :: #create_parameter_request{}.
-type parameter_create_error() :: 'project_not_exists' | 'parameter_already_exists' | 'parent_not_exists' | 'parent_is_independent' | 'parameter_source_already_exists'.
-type rename_parameter_request() :: #rename_parameter_request{}.
-type parameter_rename_error() :: 'parameter_not_exists' | 'title_already_exists'.
-type parameter_delete_error() :: 'parameter_not_exists' | 'has_children' | 'has_dependants'.
-type add_parameter_value_request() :: #add_parameter_value_request{}.
-type parameter_value_add_error() :: 'parameter_not_exists' | 'parameter_source_not_exists' | 'value_already_exists' | 'value_not_exists' | 'dependent_parameter_not_exists' | 'dependent_source_not_exists' | 'dependent_value_not_exists'.
-type rename_parameter_value_request() :: #rename_parameter_value_request{}.
-type parameter_value_rename_error() :: 'parameter_not_exists' | 'invalid_parameter' | 'value_not_exists' | 'value_already_exists'.
-type remove_parameter_value_request() :: #remove_parameter_value_request{}.
-type parameter_value_remove_error() :: 'parameter_not_exists' | 'value_not_exists' | 'linked_to_children' | 'linked_to_dependants' | 'dependent_parameter_not_exists' | 'dependent_source_not_exists' | 'dependent_value_not_exists'.

-spec parameter_create_error_to_string(parameter_create_error()) -> binary().

parameter_create_error_to_string(project_not_exists) -> <<"project_not_exists">>;
parameter_create_error_to_string(parameter_already_exists) -> <<"parameter_already_exists">>;
parameter_create_error_to_string(parent_not_exists) -> <<"parent_not_exists">>;
parameter_create_error_to_string(parent_is_independent) -> <<"parent_is_independent">>;
parameter_create_error_to_string(parameter_source_already_exists) -> <<"parameter_source_already_exists">>.

-spec parameter_create_error_from_string(binary()) -> parameter_create_error().

parameter_create_error_from_string(<<"project_not_exists">>) -> project_not_exists;
parameter_create_error_from_string(<<"parameter_already_exists">>) -> parameter_already_exists;
parameter_create_error_from_string(<<"parent_not_exists">>) -> parent_not_exists;
parameter_create_error_from_string(<<"parent_is_independent">>) -> parent_is_independent;
parameter_create_error_from_string(<<"parameter_source_already_exists">>) -> parameter_source_already_exists.

-spec parameter_create_error_to_json(parameter_create_error()) -> igor_json:json_string().

parameter_create_error_to_json(project_not_exists) -> <<"project_not_exists">>;
parameter_create_error_to_json(parameter_already_exists) -> <<"parameter_already_exists">>;
parameter_create_error_to_json(parent_not_exists) -> <<"parent_not_exists">>;
parameter_create_error_to_json(parent_is_independent) -> <<"parent_is_independent">>;
parameter_create_error_to_json(parameter_source_already_exists) -> <<"parameter_source_already_exists">>.

-spec parameter_create_error_from_json(igor_json:json()) -> parameter_create_error().

parameter_create_error_from_json(<<"project_not_exists">>) -> project_not_exists;
parameter_create_error_from_json(<<"parameter_already_exists">>) -> parameter_already_exists;
parameter_create_error_from_json(<<"parent_not_exists">>) -> parent_not_exists;
parameter_create_error_from_json(<<"parent_is_independent">>) -> parent_is_independent;
parameter_create_error_from_json(<<"parameter_source_already_exists">>) -> parameter_source_already_exists.

-spec parameter_rename_error_to_string(parameter_rename_error()) -> binary().

parameter_rename_error_to_string(parameter_not_exists) -> <<"parameter_not_exists">>;
parameter_rename_error_to_string(title_already_exists) -> <<"title_already_exists">>.

-spec parameter_rename_error_from_string(binary()) -> parameter_rename_error().

parameter_rename_error_from_string(<<"parameter_not_exists">>) -> parameter_not_exists;
parameter_rename_error_from_string(<<"title_already_exists">>) -> title_already_exists.

-spec parameter_rename_error_to_json(parameter_rename_error()) -> igor_json:json_string().

parameter_rename_error_to_json(parameter_not_exists) -> <<"parameter_not_exists">>;
parameter_rename_error_to_json(title_already_exists) -> <<"title_already_exists">>.

-spec parameter_rename_error_from_json(igor_json:json()) -> parameter_rename_error().

parameter_rename_error_from_json(<<"parameter_not_exists">>) -> parameter_not_exists;
parameter_rename_error_from_json(<<"title_already_exists">>) -> title_already_exists.

-spec parameter_delete_error_to_string(parameter_delete_error()) -> binary().

parameter_delete_error_to_string(parameter_not_exists) -> <<"parameter_not_exists">>;
parameter_delete_error_to_string(has_children) -> <<"has_children">>;
parameter_delete_error_to_string(has_dependants) -> <<"has_dependants">>.

-spec parameter_delete_error_from_string(binary()) -> parameter_delete_error().

parameter_delete_error_from_string(<<"parameter_not_exists">>) -> parameter_not_exists;
parameter_delete_error_from_string(<<"has_children">>) -> has_children;
parameter_delete_error_from_string(<<"has_dependants">>) -> has_dependants.

-spec parameter_delete_error_to_json(parameter_delete_error()) -> igor_json:json_string().

parameter_delete_error_to_json(parameter_not_exists) -> <<"parameter_not_exists">>;
parameter_delete_error_to_json(has_children) -> <<"has_children">>;
parameter_delete_error_to_json(has_dependants) -> <<"has_dependants">>.

-spec parameter_delete_error_from_json(igor_json:json()) -> parameter_delete_error().

parameter_delete_error_from_json(<<"parameter_not_exists">>) -> parameter_not_exists;
parameter_delete_error_from_json(<<"has_children">>) -> has_children;
parameter_delete_error_from_json(<<"has_dependants">>) -> has_dependants.

-spec parameter_value_add_error_to_string(parameter_value_add_error()) -> binary().

parameter_value_add_error_to_string(parameter_not_exists) -> <<"parameter_not_exists">>;
parameter_value_add_error_to_string(parameter_source_not_exists) -> <<"parameter_source_not_exists">>;
parameter_value_add_error_to_string(value_already_exists) -> <<"value_already_exists">>;
parameter_value_add_error_to_string(value_not_exists) -> <<"value_not_exists">>;
parameter_value_add_error_to_string(dependent_parameter_not_exists) -> <<"dependent_parameter_not_exists">>;
parameter_value_add_error_to_string(dependent_source_not_exists) -> <<"dependent_source_not_exists">>;
parameter_value_add_error_to_string(dependent_value_not_exists) -> <<"dependent_value_not_exists">>.

-spec parameter_value_add_error_from_string(binary()) -> parameter_value_add_error().

parameter_value_add_error_from_string(<<"parameter_not_exists">>) -> parameter_not_exists;
parameter_value_add_error_from_string(<<"parameter_source_not_exists">>) -> parameter_source_not_exists;
parameter_value_add_error_from_string(<<"value_already_exists">>) -> value_already_exists;
parameter_value_add_error_from_string(<<"value_not_exists">>) -> value_not_exists;
parameter_value_add_error_from_string(<<"dependent_parameter_not_exists">>) -> dependent_parameter_not_exists;
parameter_value_add_error_from_string(<<"dependent_source_not_exists">>) -> dependent_source_not_exists;
parameter_value_add_error_from_string(<<"dependent_value_not_exists">>) -> dependent_value_not_exists.

-spec parameter_value_add_error_to_json(parameter_value_add_error()) -> igor_json:json_string().

parameter_value_add_error_to_json(parameter_not_exists) -> <<"parameter_not_exists">>;
parameter_value_add_error_to_json(parameter_source_not_exists) -> <<"parameter_source_not_exists">>;
parameter_value_add_error_to_json(value_already_exists) -> <<"value_already_exists">>;
parameter_value_add_error_to_json(value_not_exists) -> <<"value_not_exists">>;
parameter_value_add_error_to_json(dependent_parameter_not_exists) -> <<"dependent_parameter_not_exists">>;
parameter_value_add_error_to_json(dependent_source_not_exists) -> <<"dependent_source_not_exists">>;
parameter_value_add_error_to_json(dependent_value_not_exists) -> <<"dependent_value_not_exists">>.

-spec parameter_value_add_error_from_json(igor_json:json()) -> parameter_value_add_error().

parameter_value_add_error_from_json(<<"parameter_not_exists">>) -> parameter_not_exists;
parameter_value_add_error_from_json(<<"parameter_source_not_exists">>) -> parameter_source_not_exists;
parameter_value_add_error_from_json(<<"value_already_exists">>) -> value_already_exists;
parameter_value_add_error_from_json(<<"value_not_exists">>) -> value_not_exists;
parameter_value_add_error_from_json(<<"dependent_parameter_not_exists">>) -> dependent_parameter_not_exists;
parameter_value_add_error_from_json(<<"dependent_source_not_exists">>) -> dependent_source_not_exists;
parameter_value_add_error_from_json(<<"dependent_value_not_exists">>) -> dependent_value_not_exists.

-spec parameter_value_rename_error_to_string(parameter_value_rename_error()) -> binary().

parameter_value_rename_error_to_string(parameter_not_exists) -> <<"parameter_not_exists">>;
parameter_value_rename_error_to_string(invalid_parameter) -> <<"invalid_parameter">>;
parameter_value_rename_error_to_string(value_not_exists) -> <<"value_not_exists">>;
parameter_value_rename_error_to_string(value_already_exists) -> <<"value_already_exists">>.

-spec parameter_value_rename_error_from_string(binary()) -> parameter_value_rename_error().

parameter_value_rename_error_from_string(<<"parameter_not_exists">>) -> parameter_not_exists;
parameter_value_rename_error_from_string(<<"invalid_parameter">>) -> invalid_parameter;
parameter_value_rename_error_from_string(<<"value_not_exists">>) -> value_not_exists;
parameter_value_rename_error_from_string(<<"value_already_exists">>) -> value_already_exists.

-spec parameter_value_rename_error_to_json(parameter_value_rename_error()) -> igor_json:json_string().

parameter_value_rename_error_to_json(parameter_not_exists) -> <<"parameter_not_exists">>;
parameter_value_rename_error_to_json(invalid_parameter) -> <<"invalid_parameter">>;
parameter_value_rename_error_to_json(value_not_exists) -> <<"value_not_exists">>;
parameter_value_rename_error_to_json(value_already_exists) -> <<"value_already_exists">>.

-spec parameter_value_rename_error_from_json(igor_json:json()) -> parameter_value_rename_error().

parameter_value_rename_error_from_json(<<"parameter_not_exists">>) -> parameter_not_exists;
parameter_value_rename_error_from_json(<<"invalid_parameter">>) -> invalid_parameter;
parameter_value_rename_error_from_json(<<"value_not_exists">>) -> value_not_exists;
parameter_value_rename_error_from_json(<<"value_already_exists">>) -> value_already_exists.

-spec parameter_value_remove_error_to_string(parameter_value_remove_error()) -> binary().

parameter_value_remove_error_to_string(parameter_not_exists) -> <<"parameter_not_exists">>;
parameter_value_remove_error_to_string(value_not_exists) -> <<"value_not_exists">>;
parameter_value_remove_error_to_string(linked_to_children) -> <<"linked_to_children">>;
parameter_value_remove_error_to_string(linked_to_dependants) -> <<"linked_to_dependants">>;
parameter_value_remove_error_to_string(dependent_parameter_not_exists) -> <<"dependent_parameter_not_exists">>;
parameter_value_remove_error_to_string(dependent_source_not_exists) -> <<"dependent_source_not_exists">>;
parameter_value_remove_error_to_string(dependent_value_not_exists) -> <<"dependent_value_not_exists">>.

-spec parameter_value_remove_error_from_string(binary()) -> parameter_value_remove_error().

parameter_value_remove_error_from_string(<<"parameter_not_exists">>) -> parameter_not_exists;
parameter_value_remove_error_from_string(<<"value_not_exists">>) -> value_not_exists;
parameter_value_remove_error_from_string(<<"linked_to_children">>) -> linked_to_children;
parameter_value_remove_error_from_string(<<"linked_to_dependants">>) -> linked_to_dependants;
parameter_value_remove_error_from_string(<<"dependent_parameter_not_exists">>) -> dependent_parameter_not_exists;
parameter_value_remove_error_from_string(<<"dependent_source_not_exists">>) -> dependent_source_not_exists;
parameter_value_remove_error_from_string(<<"dependent_value_not_exists">>) -> dependent_value_not_exists.

-spec parameter_value_remove_error_to_json(parameter_value_remove_error()) -> igor_json:json_string().

parameter_value_remove_error_to_json(parameter_not_exists) -> <<"parameter_not_exists">>;
parameter_value_remove_error_to_json(value_not_exists) -> <<"value_not_exists">>;
parameter_value_remove_error_to_json(linked_to_children) -> <<"linked_to_children">>;
parameter_value_remove_error_to_json(linked_to_dependants) -> <<"linked_to_dependants">>;
parameter_value_remove_error_to_json(dependent_parameter_not_exists) -> <<"dependent_parameter_not_exists">>;
parameter_value_remove_error_to_json(dependent_source_not_exists) -> <<"dependent_source_not_exists">>;
parameter_value_remove_error_to_json(dependent_value_not_exists) -> <<"dependent_value_not_exists">>.

-spec parameter_value_remove_error_from_json(igor_json:json()) -> parameter_value_remove_error().

parameter_value_remove_error_from_json(<<"parameter_not_exists">>) -> parameter_not_exists;
parameter_value_remove_error_from_json(<<"value_not_exists">>) -> value_not_exists;
parameter_value_remove_error_from_json(<<"linked_to_children">>) -> linked_to_children;
parameter_value_remove_error_from_json(<<"linked_to_dependants">>) -> linked_to_dependants;
parameter_value_remove_error_from_json(<<"dependent_parameter_not_exists">>) -> dependent_parameter_not_exists;
parameter_value_remove_error_from_json(<<"dependent_source_not_exists">>) -> dependent_source_not_exists;
parameter_value_remove_error_from_json(<<"dependent_value_not_exists">>) -> dependent_value_not_exists.

-spec create_parameter_request_to_json(create_parameter_request()) -> igor_json:json_object().

create_parameter_request_to_json(Record) ->
    #create_parameter_request{parent_id = ParentId, dependent_id = DependentId, title = Title} = Record,
    ?assert(Title =/= undefined),
    #{
        <<"parent_id">> => igor_json:pack(ParentId, long),
        <<"dependent_id">> => igor_json:pack(DependentId, long),
        <<"title">> => igor_json:pack(Title, string)
    }.

-spec create_parameter_request_from_json(igor_json:json_object()) -> create_parameter_request().

create_parameter_request_from_json(Json) ->
    ParentId = igor_json:parse(Json, <<"parent_id">>, long, undefined),
    DependentId = igor_json:parse(Json, <<"dependent_id">>, long, undefined),
    Title = igor_json:parse(Json, <<"title">>, string),
    #create_parameter_request{parent_id = ParentId, dependent_id = DependentId, title = Title}.

-spec rename_parameter_request_to_json(rename_parameter_request()) -> igor_json:json_object().

rename_parameter_request_to_json(Record) ->
    #rename_parameter_request{new_title = NewTitle} = Record,
    ?assert(NewTitle =/= undefined),
    #{
        <<"new_title">> => igor_json:pack(NewTitle, string)
    }.

-spec rename_parameter_request_from_json(igor_json:json_object()) -> rename_parameter_request().

rename_parameter_request_from_json(Json) ->
    NewTitle = igor_json:parse(Json, <<"new_title">>, string),
    #rename_parameter_request{new_title = NewTitle}.

-spec add_parameter_value_request_to_json(add_parameter_value_request()) -> igor_json:json_object().

add_parameter_value_request_to_json(Record) ->
    #add_parameter_value_request{dependent_value = DependentValue, value = VarValue} = Record,
    ?assert(VarValue =/= undefined),
    #{
        <<"dependent_value">> => igor_json:pack(DependentValue, string),
        <<"value">> => igor_json:pack(VarValue, string)
    }.

-spec add_parameter_value_request_from_json(igor_json:json_object()) -> add_parameter_value_request().

add_parameter_value_request_from_json(Json) ->
    DependentValue = igor_json:parse(Json, <<"dependent_value">>, string, undefined),
    VarValue = igor_json:parse(Json, <<"value">>, string),
    #add_parameter_value_request{dependent_value = DependentValue, value = VarValue}.

-spec rename_parameter_value_request_to_json(rename_parameter_value_request()) -> igor_json:json_object().

rename_parameter_value_request_to_json(Record) ->
    #rename_parameter_value_request{old_value = OldValue, new_value = NewValue} = Record,
    ?assert(OldValue =/= undefined),
    ?assert(NewValue =/= undefined),
    #{
        <<"old_value">> => igor_json:pack(OldValue, string),
        <<"new_value">> => igor_json:pack(NewValue, string)
    }.

-spec rename_parameter_value_request_from_json(igor_json:json_object()) -> rename_parameter_value_request().

rename_parameter_value_request_from_json(Json) ->
    OldValue = igor_json:parse(Json, <<"old_value">>, string),
    NewValue = igor_json:parse(Json, <<"new_value">>, string),
    #rename_parameter_value_request{old_value = OldValue, new_value = NewValue}.

-spec remove_parameter_value_request_to_json(remove_parameter_value_request()) -> igor_json:json_object().

remove_parameter_value_request_to_json(Record) ->
    #remove_parameter_value_request{dependent_value = DependentValue, value = VarValue} = Record,
    ?assert(VarValue =/= undefined),
    #{
        <<"dependent_value">> => igor_json:pack(DependentValue, string),
        <<"value">> => igor_json:pack(VarValue, string)
    }.

-spec remove_parameter_value_request_from_json(igor_json:json_object()) -> remove_parameter_value_request().

remove_parameter_value_request_from_json(Json) ->
    DependentValue = igor_json:parse(Json, <<"dependent_value">>, string, undefined),
    VarValue = igor_json:parse(Json, <<"value">>, string),
    #remove_parameter_value_request{dependent_value = DependentValue, value = VarValue}.

