%% @author Igor compiler
%% @doc Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-module(protocol_attachment).

-export([
    file_attachment_order_by_to_string/1,
    file_attachment_order_by_from_string/1,
    file_attachment_order_by_to_json/1,
    file_attachment_order_by_from_json/1
]).

-export_type([
    file_attachment_order_by/0
]).

-type file_attachment_order_by() :: 'id' | 'file_size' | 'original_filename' | 'content_type' | 'personnel_id' | 'personnel_name' | 'created_at'.

-spec file_attachment_order_by_to_string(file_attachment_order_by()) -> binary().

file_attachment_order_by_to_string(id) -> <<"id">>;
file_attachment_order_by_to_string(file_size) -> <<"file_size">>;
file_attachment_order_by_to_string(original_filename) -> <<"original_filename">>;
file_attachment_order_by_to_string(content_type) -> <<"content_type">>;
file_attachment_order_by_to_string(personnel_id) -> <<"personnel_id">>;
file_attachment_order_by_to_string(personnel_name) -> <<"personnel_name">>;
file_attachment_order_by_to_string(created_at) -> <<"created_at">>.

-spec file_attachment_order_by_from_string(binary()) -> file_attachment_order_by().

file_attachment_order_by_from_string(<<"id">>) -> id;
file_attachment_order_by_from_string(<<"file_size">>) -> file_size;
file_attachment_order_by_from_string(<<"original_filename">>) -> original_filename;
file_attachment_order_by_from_string(<<"content_type">>) -> content_type;
file_attachment_order_by_from_string(<<"personnel_id">>) -> personnel_id;
file_attachment_order_by_from_string(<<"personnel_name">>) -> personnel_name;
file_attachment_order_by_from_string(<<"created_at">>) -> created_at.

-spec file_attachment_order_by_to_json(file_attachment_order_by()) -> igor_json:json_string().

file_attachment_order_by_to_json(id) -> <<"id">>;
file_attachment_order_by_to_json(file_size) -> <<"file_size">>;
file_attachment_order_by_to_json(original_filename) -> <<"original_filename">>;
file_attachment_order_by_to_json(content_type) -> <<"content_type">>;
file_attachment_order_by_to_json(personnel_id) -> <<"personnel_id">>;
file_attachment_order_by_to_json(personnel_name) -> <<"personnel_name">>;
file_attachment_order_by_to_json(created_at) -> <<"created_at">>.

-spec file_attachment_order_by_from_json(igor_json:json()) -> file_attachment_order_by().

file_attachment_order_by_from_json(<<"id">>) -> id;
file_attachment_order_by_from_json(<<"file_size">>) -> file_size;
file_attachment_order_by_from_json(<<"original_filename">>) -> original_filename;
file_attachment_order_by_from_json(<<"content_type">>) -> content_type;
file_attachment_order_by_from_json(<<"personnel_id">>) -> personnel_id;
file_attachment_order_by_from_json(<<"personnel_name">>) -> personnel_name;
file_attachment_order_by_from_json(<<"created_at">>) -> created_at.

