%% Author: Igor compiler
%% Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-record(create_jira_instance_request, {
    title :: binary(),
    url :: binary()
}).

-record(update_jira_instance_request, {
    title :: binary() | 'undefined' | 'null',
    url :: binary() | 'undefined' | 'null'
}).

-record(create_jira_issue_request, {
    summary :: binary(),
    description :: binary()
}).

-record(create_jira_issue_response, {
    jira_issue_key :: binary(),
    jira_issue_url :: binary()
}).

-record(authenticate_jira_request, {
    username :: binary(),
    password :: binary()
}).

