%% Author: Igor compiler
%% Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-record(create_test_run_request, {
    title :: binary() | 'undefined'
}).

-record(update_test_run_request, {
    title :: binary() | 'undefined' | 'null'
}).

-record(create_test_run_item_request, {
    case_id :: igor_types:long(),
    order_num :: igor_types:int()
}).

-record(update_test_run_item_request, {
    summary :: binary() | 'undefined' | 'null',
    order_num :: igor_types:int() | 'undefined',
    jira_issue_key :: binary() | 'undefined' | 'null'
}).

-record(finish_test_run_item_request, {
    summary :: binary() | 'undefined'
}).

-record(block_test_run_item_request, {
    failed_setup_id :: igor_types:long(),
    setup_parameter_value :: binary() | 'undefined',
    summary :: binary() | 'undefined'
}).

