%% Author: Igor compiler
%% Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-record(create_setup_step_request, {
    parent_id :: igor_types:long() | 'undefined',
    title :: binary(),
    description :: binary() | 'undefined',
    is_draft :: boolean(),
    order_num :: igor_types:int()
}).

-record(update_setup_step_request, {
    parent_id :: igor_types:long() | 'undefined' | 'null',
    title :: binary() | 'undefined',
    description :: binary() | 'undefined',
    is_draft :: boolean() | 'undefined',
    order_num :: igor_types:int() | 'undefined'
}).

