%% Author: Igor compiler
%% Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-record(create_project_request, {
    title :: binary(),
    key :: binary(),
    jira_id :: igor_types:long() | 'undefined',
    jira_key :: binary() | 'undefined',
    slack_receivers :: binary() | 'undefined'
}).

-record(update_project_request, {
    title :: binary() | 'undefined',
    key :: binary() | 'undefined',
    jira_id :: igor_types:long() | 'undefined' | 'null',
    jira_key :: binary() | 'undefined' | 'null',
    slack_receivers :: binary() | 'undefined' | 'null'
}).

