%% Author: Igor compiler
%% Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-record(personnel_status_response, {
    logged_in :: boolean(),
    user_id :: igor_types:long() | 'undefined',
    email :: binary() | 'undefined',
    username :: binary() | 'undefined'
}).

-record(personnel_login_request, {
    username :: binary(),
    password :: binary()
}).

-record(personnel_login_response, {
    result :: boolean(),
    error :: protocol_auth:personnel_login_error() | 'undefined',
    session_id :: binary() | 'undefined',
    user_id :: igor_types:long() | 'undefined',
    email :: binary() | 'undefined',
    username :: binary() | 'undefined'
}).

