%% Author: Igor compiler
%% Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-record(create_test_case_request, {
    parent_id :: igor_types:long() | 'undefined',
    precondition_id :: igor_types:long() | 'undefined',
    setup_id :: igor_types:long() | 'undefined',
    is_group :: boolean(),
    title :: binary(),
    description :: binary() | 'undefined',
    test_steps :: binary(),
    expected_result :: binary(),
    is_draft :: boolean(),
    order_num :: igor_types:int()
}).

-record(update_test_case_request, {
    parent_id :: igor_types:long() | 'undefined' | 'null',
    precondition_id :: igor_types:long() | 'undefined' | 'null',
    setup_id :: igor_types:long() | 'undefined' | 'null',
    title :: binary() | 'undefined',
    description :: binary() | 'undefined',
    test_steps :: binary() | 'undefined',
    expected_result :: binary() | 'undefined',
    is_draft :: boolean() | 'undefined',
    order_num :: igor_types:int() | 'undefined'
}).

-record(specialize_test_case_request, {
    spec_type :: protocol_db:spec_type(),
    value :: binary() | 'undefined',
    parameter_id :: igor_types:long() | 'undefined'
}).

