%% Author: Igor compiler
%% Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-record(settings, {
    personnel_session_duration :: igor_types:int()
}).

-record(settings_update_request, {
    personnel_session_duration :: igor_types:int() | 'undefined'
}).

