%% Author: Igor compiler
%% Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-record(file, {
    id :: binary(),
    created :: igor_types:int(),
    timestamp :: igor_types:int(),
    name :: binary(),
    title :: binary(),
    mimetype :: binary(),
    filetype :: binary(),
    pretty_type :: binary(),
    user :: binary(),
    editable :: boolean(),
    size :: igor_types:int(),
    mode :: slack_protocol:file_mode(),
    is_external :: boolean(),
    external_type :: binary(),
    is_public :: boolean(),
    public_url_shared :: boolean(),
    display_as_bot :: boolean(),
    username :: binary(),
    url_private :: binary(),
    url_private_download :: binary(),
    permalink :: binary(),
    permalink_public :: binary(),
    edit_link :: binary(),
    preview :: binary(),
    preview_highlight :: binary(),
    lines :: igor_types:int(),
    lines_more :: igor_types:int(),
    preview_is_truncated :: boolean(),
    comments_count :: igor_types:int(),
    is_starred :: boolean(),
    shares :: igor_json:json(),
    channels :: [binary()],
    groups :: [binary()],
    ims :: [binary()],
    has_rich_preview :: boolean()
}).

-record(message, {
    type :: binary(),
    subtype :: binary(),
    text :: binary(),
    ts :: binary(),
    username :: binary(),
    bot_id :: binary()
}).

-record(post_message_request, {
    channel :: binary(),
    text :: binary()
}).

-record(attachment_field, {
    title :: binary(),
    value :: binary(),
    short = false :: boolean()
}).

-record(attachment_block, {
    fallback :: binary() | 'undefined',
    color :: binary() | 'undefined',
    pretext :: binary() | 'undefined',
    author_name :: binary() | 'undefined',
    author_link :: binary() | 'undefined',
    author_icon :: binary() | 'undefined',
    title :: binary() | 'undefined',
    title_link :: binary() | 'undefined',
    text :: binary() | 'undefined',
    fields :: [slack_protocol:attachment_field()] | 'undefined',
    image_url :: binary() | 'undefined',
    thumb_url :: binary() | 'undefined',
    footer :: binary() | 'undefined',
    footer_icon :: binary() | 'undefined',
    ts :: igor_types:int() | 'undefined'
}).

-record(post_message_ex_request, {
    channel :: binary(),
    text :: binary(),
    mrkdwn = false :: boolean(),
    attachments :: [slack_protocol:attachment_block()]
}).

-record(post_message_response, {
    ok :: boolean(),
    channel :: binary() | 'undefined',
    ts :: binary() | 'undefined',
    message :: slack_protocol:message() | 'undefined',
    error :: binary() | 'undefined'
}).

-record(post_snippet_request, {
    channels :: binary(),
    title :: binary(),
    initial_comment :: binary(),
    content :: binary()
}).

-record(post_snippet_response, {
    ok :: boolean(),
    file :: slack_protocol:file() | 'undefined'
}).

-record(get_users_response, {
    ok :: boolean(),
    members :: [slack_protocol:member()]
}).

-record(member, {
    id :: binary(),
    profile :: slack_protocol:member_profile()
}).

-record(member_profile, {
    real_name :: binary(),
    display_name :: binary()
}).

-record(channel, {
    id :: binary()
}).

