%% Author: Igor compiler
%% Compiler version: igorc 2.1.1
%% DO NOT EDIT THIS FILE - it is machine generated

-record(fields, {
    fields :: _T
}).

-record(key_object, {
    key :: _T
}).

-record(name_object, {
    name :: _T
}).

-record(create_issue_request, {
    project :: jira_protocol:key_object(binary()),
    summary :: binary(),
    description :: binary(),
    issuetype :: jira_protocol:name_object(jira_protocol:issue_type())
}).

-record(create_issue_response, {
    id :: binary(),
    key :: binary(),
    self :: binary()
}).

-record(jira_item_collection, {
    size :: igor_types:int(),
    items :: [_T]
}).

-record(jira_group_entry, {
    name :: binary(),
    self :: binary()
}).

-record(get_user_response, {
    self :: binary(),
    name :: binary(),
    email_address :: binary(),
    avatar_urls :: igor_json:json(),
    display_name :: binary(),
    active :: boolean(),
    time_zone :: binary(),
    groups :: jira_protocol:jira_item_collection(jira_protocol:jira_group_entry()),
    application_roles :: jira_protocol:jira_item_collection(igor_json:json()),
    expand :: binary()
}).

-record(jira_response400, {
    error_messages = [] :: [binary()],
    errors :: igor_json:json() | 'undefined'
}).

-record(jira_response404, {
}).

